SET client_encoding = 'UTF8';

CREATE SCHEMA IF NOT EXISTS cut_url;

CREATE TABLE IF NOT EXISTS cut_url.urls
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_url  text        NOT NULL,
    cut_url     varchar(10) NOT NULL,
    create_date timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS urls_cut_url_key ON cut_url.urls (cut_url);

CREATE UNIQUE INDEX IF NOT EXISTS urls_origin_url_key ON cut_url.urls (origin_url);

COMMENT ON TABLE cut_url.urls IS 'Сокращённые ссылки: один оригинальный URL - один короткий код';
COMMENT ON COLUMN cut_url.urls.origin_url IS 'Исходный URL, уникален';
COMMENT ON COLUMN cut_url.urls.cut_url IS 'Короткий код из 10 символов [a-zA-Z0-9_], уникален';
COMMENT ON COLUMN cut_url.urls.create_date IS 'Момент создания записи';
